In [2]:
import os
import pandas as pd
import numpy as np

files = os.listdir("data/raw")

dfs = []
for file in files:
    if file.endswith(".csv"):
        dfs.append(pd.read_csv(f"data/raw/{file}"))

df = pd.concat(dfs, ignore_index=True)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6161 entries, 0 to 6160
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   HealthTopic  6161 non-null   object
 1   Population   6161 non-null   object
 2   Indicator    6161 non-null   object
 3   Unit         6161 non-null   object
 4   Time         6161 non-null   int64
 5   RegionCode   6161 non-null   object
 6   RegionName   6161 non-null   object
 7   NumValue     6161 non-null   object
 8   TxtValue     0 non-null      float64
dtypes: float64(1), int64(1), object(7)
memory usage: 433.3+ KB

In [4]:
df.head()

,HealthTopic,Population,Indicator,Unit,Time,RegionCode,RegionName,NumValue,TxtValue
0,Antimicrobial resistance,Acinetobacter spp.|Aminoglycosides,"R - resistant isolates, percentage",%,2012,BG,Bulgaria,58.461538460,NaN
1,Antimicrobial resistance,Acinetobacter spp.|Aminoglycosides,"R - resistant isolates, percentage",%,2012,CY,Cyprus,52.173913040,NaN
2,Antimicrobial resistance,Acinetobacter spp.|Aminoglycosides,"R - resistant isolates, percentage",%,2012,DE,Germany,5.882352940,NaN
3,Antimicrobial resistance,Acinetobacter spp.|Aminoglycosides,"R - resistant isolates, percentage",%,2012,DK,Denmark,10.389610380,NaN
4,Antimicrobial resistance,Acinetobacter spp.|Aminoglycosides,"R - resistant isolates, percentage",%,2012,EL,Greece,78.119935170,NaN

In [5]:
df.columns

Index(['HealthTopic', 'Population', 'Indicator', 'Unit', 'Time', 'RegionCode',
       'RegionName', 'NumValue', 'TxtValue'],
      dtype='object')

In [6]:
df[["Bacteria", "AntibioticGroup"]] = df["Population"].str.split("|", expand=True)

In [7]:
df[["Population", "Bacteria", "AntibioticGroup"]].head()

                           Population            Bacteria  AntibioticGroup
0  Acinetobacter spp.|Aminoglycosides  Acinetobacter spp.  Aminoglycosides
1  Acinetobacter spp.|Aminoglycosides  Acinetobacter spp.  Aminoglycosides
2  Acinetobacter spp.|Aminoglycosides  Acinetobacter spp.  Aminoglycosides
3  Acinetobacter spp.|Aminoglycosides  Acinetobacter spp.  Aminoglycosides
4  Acinetobacter spp.|Aminoglycosides  Acinetobacter spp.  Aminoglycosides

In [8]:
df.head()

,HealthTopic,Population,Indicator,Unit,Time,RegionCode,RegionName,NumValue,TxtValue,Bacteria,AntibioticGroup
0,Antimicrobial resistance,Acinetobacter spp.|Aminoglycosides,"R - resistant isolates, percentage",%,2012,BG,Bulgaria,58.461538460,NaN,Acinetobacter spp.,Aminoglycosides
1,Antimicrobial resistance,Acinetobacter spp.|Aminoglycosides,"R - resistant isolates, percentage",%,2012,CY,Cyprus,52.173913040,NaN,Acinetobacter spp.,Aminoglycosides
2,Antimicrobial resistance,Acinetobacter spp.|Aminoglycosides,"R - resistant isolates, percentage",%,2012,DE,Germany,5.882352940,NaN,Acinetobacter spp.,Aminoglycosides
3,Antimicrobial resistance,Acinetobacter spp.|Aminoglycosides,"R - resistant isolates, percentage",%,2012,DK,Denmark,10.389610380,NaN,Acinetobacter spp.,Aminoglycosides
4,Antimicrobial resistance,Acinetobacter spp.|Aminoglycosides,"R - resistant isolates, percentage",%,2012,EL,Greece,78.119935170,NaN,Acinetobacter spp.,Aminoglycosides

In [9]:
df.drop(columns=["HealthTopic", "Population", "Unit", "Indicator", "TxtValue"], inplace=True)

In [10]:
df.rename(columns={"Time": "Year", "RegionCode": "CountryCode", "RegionName": "Country", "NumValue": "Resistance_Percentage"}, inplace=True)

In [11]:
df = df[["Bacteria", "AntibioticGroup", "Year", "CountryCode", "Country", "Resistance_Percentage"]]

In [12]:
df.head()

,Bacteria,AntibioticGroup,Year,CountryCode,Country,Resistance_Percentage
0,Acinetobacter spp.,Aminoglycosides,2012,BG,Bulgaria,58.461538460
1,Acinetobacter spp.,Aminoglycosides,2012,CY,Cyprus,52.173913040
2,Acinetobacter spp.,Aminoglycosides,2012,DE,Germany,5.882352940
3,Acinetobacter spp.,Aminoglycosides,2012,DK,Denmark,10.389610380
4,Acinetobacter spp.,Aminoglycosides,2012,EL,Greece,78.119935170

In [13]:
def eda_amr(df):
    """
    Analisis exploratorio completo para dataset de resistencia antimicrobiana (AMR)
    """
    
    print("🔎 PRIMER VISTAZO A LOS DATOS")
    print("Primeras filas:")
    display(df.head())
    
    print("\nUltimas filas:")
    display(df.tail())
    
    print("\nMuestra aleatoria:")
    display(df.sample(5))
    
    
    print("\n📐 ESTRUCTURA DEL DATAFRAME")
    print(f"Dimensiones (filas, columnas): {df.shape}\n")
    
    print("Columnas:")
    display(df.columns)
    
    print("\nInformacion general:")
    df.info()
    
    print("\nTipos de datos por columna:")
    display(df.dtypes)
    
    
    print("\n📊 ESTADISTICAS DESCRIPTIVAS")
    print("Variables numericas:")
    display(df.describe().T)
    
    print("\nVariables categoricas:")
    display(df.describe(include='object').T)
    
    
    print("\n🔢 CARDINALIDAD")
    print("Numero de valores unicos por columna:")
    display(df.nunique())
    
    
    print("\n🧩 VALORES UNICOS CLAVE")
    
    print("\nBacterias:")
    display(df["Bacteria"].unique())
    
    print("\nGrupos antibioticos:")
    display(df["AntibioticGroup"].unique())
    
    print("\nAños:")
    display(sorted(df["Year"].unique()))
    
    print("\nPaises (primeros 20):")
    display(df["Country"].unique()[:20])
    
    
    print("\n🚨 VALORES NULOS")
    display(df.isnull().sum())
    
    print("\nPorcentaje de valores nulos (%)")
    display(((df.isnull().sum() / df.shape[0]) * 100).round(2))
    
    
    print("\n🔁 DUPLICADOS")
    dup_count = df.duplicated(
        subset=["Bacteria","AntibioticGroup","Year","CountryCode"]
    ).sum()
    
    print(f"Duplicados segun combinacion clave: {dup_count}")
    
    if dup_count > 0:
        display(df[df.duplicated(
            subset=["Bacteria","AntibioticGroup","Year","CountryCode"],
            keep=False
        )])
    else:
        print("No hay duplicados estructurales.")   
    
    print("\n📈 DISTRIBUCION RESISTANCE_PERCENTAGE")
    display(df["Resistance_Percentage"].describe()
    )

In [14]:
eda_amr(df)

🔎 PRIMER VISTAZO A LOS DATOS
Primeras filas:

,Bacteria,AntibioticGroup,Year,CountryCode,Country,Resistance_Percentage
0,Acinetobacter spp.,Aminoglycosides,2012,BG,Bulgaria,58.461538460
1,Acinetobacter spp.,Aminoglycosides,2012,CY,Cyprus,52.173913040
2,Acinetobacter spp.,Aminoglycosides,2012,DE,Germany,5.882352940
3,Acinetobacter spp.,Aminoglycosides,2012,DK,Denmark,10.389610380
4,Acinetobacter spp.,Aminoglycosides,2012,EL,Greece,78.119935170

Ultimas filas:

,Bacteria,AntibioticGroup,Year,CountryCode,Country,Resistance_Percentage
6156,Klebsiella pneumoniae,Fluoroquinolones,2024,PT,Portugal,39.566982400
6157,Klebsiella pneumoniae,Fluoroquinolones,2024,RO,Romania,64.513350550
6158,Klebsiella pneumoniae,Fluoroquinolones,2024,SE,Sweden,13.551779930
6159,Klebsiella pneumoniae,Fluoroquinolones,2024,SI,Slovenia,20.738636360
6160,Klebsiella pneumoniae,Fluoroquinolones,2024,SK,Slovakia,50.131926120

Muestra aleatoria:

,Bacteria,AntibioticGroup,Year,CountryCode,Country,Resistance_Percentage
4325,Klebsiella pneumoniae,Aminoglycosides,2021,IE,Ireland,10.557768920
1184,Escherichia coli,Aminoglycosides,2004,CY,Cyprus,10.869565210
5423,Klebsiella pneumoniae,Third-generation cephalosporins,2019,LV,Latvia,36.868686860
54,Acinetobacter spp.,Aminoglycosides,2014,FR,France,8.312958430
5684,Klebsiella pneumoniae,Fluoroquinolones,2008,RO,Romania,-

📐 ESTRUCTURA DEL DATAFRAME
Dimensiones (filas, columnas): (6161, 6)

Columnas:

Index(['Bacteria', 'AntibioticGroup', 'Year', 'CountryCode', 'Country',
       'Resistance_Percentage'],
      dtype='object')

Informacion general:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6161 entries, 0 to 6160
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Bacteria               6161 non-null   object
 1   AntibioticGroup        6161 non-null   object
 2   Year                   6161 non-null   int64
 3   CountryCode            6161 non-null   object
 4   Country                6161 non-null   object
 5   Resistance_Percentage  6161 non-null   object
dtypes: int64(1), object(5)
memory usage: 288.9+ KB

Tipos de datos por columna:

Bacteria                 object
AntibioticGroup          object
Year                      int64
CountryCode              object
Country                  object
Resistance_Percentage    object
dtype: object

📊 ESTADISTICAS DESCRIPTIVAS
Variables numericas:

       count         mean       std     min     25%     50%     75%     max
Year  6161.0  2014.474436  6.241205  2000.0  2010.0  2015.0  2020.0  2024.0

Variables categoricas:

                      count unique               top  freq
Bacteria               6161      3  Escherichia coli  2746
AntibioticGroup        6161      4  Fluoroquinolones  1645
CountryCode            6161     31                EL   219
Country                6161     31            Greece   219
Resistance_Percentage  6161   4755       0.000000000   563

🔢 CARDINALIDAD
Numero de valores unicos por columna:

Bacteria                    3
AntibioticGroup             4
Year                       25
CountryCode                31
Country                    31
Resistance_Percentage    4755
dtype: int64

🧩 VALORES UNICOS CLAVE

Bacterias:

array(['Acinetobacter spp.', 'Escherichia coli', 'Klebsiella pneumoniae'],
      dtype=object)

Grupos antibioticos:

array(['Aminoglycosides', 'Carbapenems', 'Fluoroquinolones',
       'Third-generation cephalosporins'], dtype=object)

Años:

[np.int64(2000),
 np.int64(2001),
 np.int64(2002),
 np.int64(2003),
 np.int64(2004),
 np.int64(2005),
 np.int64(2006),
 np.int64(2007),
 np.int64(2008),
 np.int64(2009),
 np.int64(2010),
 np.int64(2011),
 np.int64(2012),
 np.int64(2013),
 np.int64(2014),
 np.int64(2015),
 np.int64(2016),
 np.int64(2017),
 np.int64(2018),
 np.int64(2019),
 np.int64(2020),
 np.int64(2021),
 np.int64(2022),
 np.int64(2023),
 np.int64(2024)]

Paises (primeros 20):

array(['Bulgaria', 'Cyprus', 'Germany', 'Denmark', 'Greece', 'France',
       'Hungary', 'Iceland', 'Italy', 'Luxembourg', 'Malta',
       'Netherlands', 'Norway', 'Poland', 'Portugal', 'Romania',
       'Slovenia', 'United Kingdom', 'Austria', 'Belgium'], dtype=object)

🚨 VALORES NULOS

Bacteria                 0
AntibioticGroup          0
Year                     0
CountryCode              0
Country                  0
Resistance_Percentage    0
dtype: int64

Porcentaje de valores nulos (%)

Bacteria                 0.0
AntibioticGroup          0.0
Year                     0.0
CountryCode              0.0
Country                  0.0
Resistance_Percentage    0.0
dtype: float64

🔁 DUPLICADOS
Duplicados segun combinacion clave: 0
No hay duplicados estructurales.

📈 DISTRIBUCION RESISTANCE_PERCENTAGE

count            6161
unique           4755
top       0.000000000
freq              563
Name: Resistance_Percentage, dtype: object

In [15]:
df["Resistance_Percentage"].head(20)

0     58.461538460
1     52.173913040
2      5.882352940
3     10.389610380
4     78.119935170
5     12.949640280
6     68.796068790
7                -
8     83.333333330
9                -
10               -
11     4.545454540
12     4.000000000
13    70.142180090
14    65.088757390
15    57.407407400
16    20.000000000
17     2.777777770
18     9.803921560
19               -
Name: Resistance_Percentage, dtype: object

In [16]:
df["Resistance_Percentage"] = (
    df["Resistance_Percentage"]
    .replace("-", np.nan)
)

In [17]:
df["Resistance_Percentage"] = df["Resistance_Percentage"].astype(float)

In [18]:
df["Resistance_Percentage"].describe()

count    5899.000000
mean       20.085531
std        23.461683
min         0.000000
25%         3.005977
50%        10.793651
75%        28.295680
max        99.753086
Name: Resistance_Percentage, dtype: float64

In [20]:
df[df["Resistance_Percentage"].isna()]

,Bacteria,AntibioticGroup,Year,CountryCode,Country,Resistance_Percentage
7,Acinetobacter spp.,Aminoglycosides,2012,IS,Iceland,NaN
9,Acinetobacter spp.,Aminoglycosides,2012,LU,Luxembourg,NaN
10,Acinetobacter spp.,Aminoglycosides,2012,MT,Malta,NaN
19,Acinetobacter spp.,Aminoglycosides,2013,BE,Belgium,NaN
33,Acinetobacter spp.,Aminoglycosides,2013,LU,Luxembourg,NaN
...,...,...,...,...,...,...
5790,Klebsiella pneumoniae,Fluoroquinolones,2012,IS,Iceland,NaN
5940,Klebsiella pneumoniae,Fluoroquinolones,2017,IS,Iceland,NaN
5970,Klebsiella pneumoniae,Fluoroquinolones,2018,IS,Iceland,NaN
6118,Klebsiella pneumoniae,Fluoroquinolones,2023,LI,Liechtenstein,NaN
6148,Klebsiella pneumoniae,Fluoroquinolones,2024,LI,Liechtenstein,NaN

In [21]:
df[df["Resistance_Percentage"].isna()] \
  .groupby("Country") \
  .size() \
  .sort_values(ascending=False)

Country
Iceland          59
Luxembourg       45
Malta            40
Estonia          32
Liechtenstein    20
Romania          20
Sweden           13
Poland           13
Cyprus            8
Belgium           7
Lithuania         2
Portugal          2
Czechia           1
dtype: int64

In [ ]:
(df.groupby("Country")["Resistance_Percentage"].apply(lambda x: x.isna().mean()).sort_values(ascending=False))

Country
Liechtenstein     1.000000
Iceland           0.290640
Luxembourg        0.213270
Malta             0.186047
Estonia           0.153110
Romania           0.094787
Sweden            0.061905
Poland            0.060748
Cyprus            0.038647
Belgium           0.037433
Lithuania         0.010811
Portugal          0.009709
Czechia           0.004785
Bulgaria          0.000000
Austria           0.000000
Ireland           0.000000
Hungary           0.000000
Greece            0.000000
Germany           0.000000
Finland           0.000000
France            0.000000
Croatia           0.000000
Denmark           0.000000
Norway            0.000000
Netherlands       0.000000
Latvia            0.000000
Italy             0.000000
Slovakia          0.000000
Slovenia          0.000000
Spain             0.000000
United Kingdom    0.000000
Name: Resistance_Percentage, dtype: float64

In [23]:
df = df[df["Country"] != "Liechtenstein"]

In [24]:
df["Country"].unique()

array(['Bulgaria', 'Cyprus', 'Germany', 'Denmark', 'Greece', 'France',
       'Hungary', 'Iceland', 'Italy', 'Luxembourg', 'Malta',
       'Netherlands', 'Norway', 'Poland', 'Portugal', 'Romania',
       'Slovenia', 'United Kingdom', 'Austria', 'Belgium', 'Czechia',
       'Spain', 'Finland', 'Croatia', 'Ireland', 'Sweden', 'Slovakia',
       'Lithuania', 'Latvia', 'Estonia'], dtype=object)

In [25]:
df.to_csv("resistance_data_cleaned.csv", index=False)